name: issue-automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]


jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Issue Labeler
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: "needs-triage, bug"
          remove-labels: "in progress"